spring:
  graphql:
    schema:
      printer:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    schema: classpath:sql/*-schema.sql
    data: classpath:sql/*-data.sql

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml